// try catch

const n1 = 24;
const n3 = 20;

console.log(n1);

try {
    console.log(n2);
} catch (error) {
    console.log(error);
}

console.log(n3);